Add to .Xresources and `lx' so xterm works.

diff --git a/scripts/lx b/scripts/lx
--- a/scripts/lx
+++ b/scripts/lx
@@ -4,15 +4,8 @@
 # Shows thumbnails of images with titles directly in terminal. 
 
 # Requirements: just ImageMagick (and a Sixel terminal, of course)
+# Based on lsix by hackerb9
 
-# Version 1.6.2
-# B9 December 2018
-
-
-# The following defaults may be overridden if autodetection succeeds.
-numcolors=256     # Default number of colors in the palette.
-background=black  # Default montage background.
-foreground=white  # Default text color.
 
 # Feel free to edit these defaults to your liking.
 tilesize=150	       # Width and height of each tile in the montage.
@@ -59,6 +52,38 @@ autodetect() {
 	EOF
 	exit 1
     fi
+
+	# TERMINAL COLOR AUTODETECTION.
+	# Find out how many color registers the terminal has
+	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;1;0S' >&2
+	[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
+	
+	# Increase colors, if needed
+	if [[ $numcolors -lt 256 ]]; then
+	# Attempt to set the number of colors to 256.
+	# This will work for xterm, but fail on a real vt340.
+	IFS=";"  read -a REPLY -s -t ${timeout} -d "S" -p $'\e[?1;3;256S' >&2
+	[[ ${REPLY[1]} == "0" ]] && numcolors=${REPLY[2]}
+	fi
+	
+	# Query the terminal background and foreground colors.
+	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]11;?\e\\' >&2
+	if [[ ${REPLY[1]} =~ ^rgb ]]; then
+	# Return value format: $'\e]11;rgb:ffff/0000/ffff\e\\'.
+	# ImageMagick wants colors formatted as #ffff0000ffff.
+	background='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+	IFS=";:/"  read -a REPLY -r -s -t ${timeout} -d "\\" -p $'\e]10;?\e\\' >&2
+	if [[ ${REPLY[1]} =~ ^rgb ]]; then
+	    foreground='#'${REPLY[2]}${REPLY[3]}${REPLY[4]%%$'\e'*}
+	    # Check for "Reverse Video".
+	    IFS=";?$"  read -a REPLY -s -t ${timeout} -d "y" -p $'\e[?5$p'
+	    if [[ ${REPLY[2]} == 1 || ${REPLY[2]} == 3 ]]; then
+		temp=$foreground
+		foreground=$background
+		background=$temp
+	    fi
+	fi
+	fi
 
     # ENABLE SIXEL SCROLLING so image will appear right after cursor.
 	echo -ne $'\e[?80h'
